/**
 * PaymentGatewayProvider — the adapter contract every payment gateway
 * implements. Same Provider Registry pattern as every other layer
 * (telephony/stt/tts/llm/embedding/whatsapp) — see
 * docs/PROVIDER_REGISTRY.md. Business logic depends ONLY on this
 * interface, obtained via `getPaymentGatewayProvider()` in
 * apps/web/lib/providers/registry.ts — never a concrete adapter class.
 *
 * Scope for Phase 7: create a payment link/order for a wallet top-up, and
 * verify + parse an inbound webhook. Subscription-charge support is a
 * natural Phase 8+ extension of the same interface, not implemented here.
 */

export type ProviderConfig = Record<string, unknown>;

export class WebhookSignatureError extends Error {
  constructor(message = "payment gateway webhook signature verification failed") {
    super(message);
    this.name = "WebhookSignatureError";
  }
}

export type CreatePaymentLinkParams = {
  orgId: string;
  /** The platform's own payment_orders.id-to-be is generated by the
   * caller (createWalletTopupOrder) BEFORE this call, and passed through
   * as a receipt/reference so the gateway's own order id can be recorded
   * against it, and so a webhook can be correlated back even if the
   * gateway's order id lookup ever changes. */
  amount: number;
  currency: string;
  description: string;
  /** Where to send the payer after completing payment (best-effort UX;
   * the wallet credit itself only ever happens via the verified webhook,
   * never via this redirect). */
  callbackUrl?: string;
};

export type CreatePaymentLinkResult = {
  /** The gateway's own order/payment-link id — stored in
   * payment_orders.provider_order_id. */
  providerOrderId: string;
  /** URL to redirect the payer to. */
  paymentUrl: string;
};

export type NormalizedPaymentWebhookEvent = {
  /** Provider event id (or a derived hash if the provider has none) —
   * used as payment_webhook_events.idempotency_key. */
  idempotencyKey: string;
  providerOrderId: string;
  eventType: string;
  /** true only for a definitively successful/captured payment event. */
  isPaymentCaptured: boolean;
  amount: number;
  currency: string;
  raw: unknown;
};

export interface PaymentGatewayProvider {
  /** Stable key matching `providers.provider_key`. */
  readonly providerKey: string;

  createPaymentLink(params: CreatePaymentLinkParams): Promise<CreatePaymentLinkResult>;

  /**
   * Verifies the webhook's signature (throws WebhookSignatureError if
   * invalid) and normalizes its payload. Callers must verify before
   * trusting anything in the returned event.
   */
  verifyAndParseWebhook(
    headers: Record<string, string | string[] | undefined>,
    rawBody: string
  ): Promise<NormalizedPaymentWebhookEvent>;
}
